### ISSUE TITLE
List of ores to support

### ISSUE THREAD

**Issue by Hypsellis** [MinecraftModDevelopmentMods/MoarTinkers#2]
I saw this mod was rewritten. I wanted to help my own way by giving a list of all usual ores by mods that could be supported.

- Vanilla
   - Gold
   - Diamond
   - Emerald
   - Quartz
   - Lapis Lazuli
   - Granite
   - Andesite
   - Diorite

- Common metals and alloys
   - Tin
   - Nickel
   - Platinium
   - Aluminum
   - Zinc
   - Invar
   - Constantan
   - Brass

- BiomesOPlenty
    - Ruby
    - Sapphire
    - Peridot
    - Topaz
    - Amethyst
    - Tanzanite
    - Amber

- Chisel/Quark
    - Marble
    - Limestone
    - Basalt

- Tinkers Construct
    - Aluminum Brass

- Thermal Expension
    - Signalum
    - Lumium
    - Enderium
    - Mithrillium (Mana Infused)
    - Iridium

- Redstone Arsenal
    - Flux Crystal
    - Fluxed Electrum

- TechReborn
    - Chromium
    - Tungsten
    - Titanium
    - Iridium
    - Refined Iron
    - Tungstensteel
    - Advanced Alloy
    - Ruby
    - Sapphire
    - Peridot
    - Red Garnet
    - Yellow Garnet

- Mekanism
    - Osmium
    - Refined Obsidian
    - Refined Glowstone

- Forestry
    - Apatite

- Applied Energetics
    - Certus Quartz
    - Fluix Quartz

- Refined Storage
    - Quartz Enriched Iron

- ProjectRed
    - Red Alloy
    - Electrotine Alloy
    - Ruby
    - Sapphire
    - Peridot

- Extreme Reactors
    - Yellorium
    - Cyanite
    - Blutorium
    - Lucidrite
    - Graphite

- Avaritia
    - Crystal Matrix
    - Infinity
    - Neutronium

- Actually Additions
    - Black Quartz
    - Redstonia
    - Palis
    - Diamatine
    - Emeradic
    - Enori
    - Void

- Draconic Evolution
    - Draconium
    - Awakened Draconium

- Thaumcraft
    - Thaumium
    - Void

- Botania
    - Living Wood
    - Living Stone
    - Manasteel
    - Terrasteel
    - Elementium
    - Gaia Spirit
    - Mana Diamond
    - Dragon Stone
    - Red Quartz
    - Blaze Quartz
    - Sunny Quartz
    - Elven Quartz
    - Mana Quartz
    - Lavender Quartz
    - Smokey Quartz

- Psi
    - Psigem
    - Psimetal
    - Ebony
    - Ivory

- Quark
    - Biotite

- Embers
    - Drawstone

- Astral Sorcery
    - Aquamarine
    - Starmetal

- ProjectE
    - Dark Matter
    - Red Matter

- Better With Mods
    - Soulforge Steel
    - Hellfire

**Comment by YaibaToKen** [comment]
> I saw this mod was rewritten. I wanted to help my own way by giving a list of all usual ores by mods that could be supported.
> 
> * Vanilla
>   
>   * ~~Gold~~
>   * ~~Diamond~~
>   * ~~Emerald~~
>   * ~~Quartz~~
>   * ~~Lapis Lazuli~~
>   * Granite
>   * Andesite
>   * Diorite

I won't be touching any vanilla materials aside from possibly Granite, Andesite and Diorite as cosmetic alternatives to Stone.

> * Common metals and alloys
>   
>   * Tin
>   * Nickel
>   * Platinium
>   * Aluminum
>   * Invar
>   * Constantan
> * BiomesOPlenty
>   
>   * Ruby
>   * Sapphire
>   * Peridot
>   * Topaz
>   * Amethyst
>   * Tanzanite
>   * Amber
> * Chisel/Quark
>   
>   * Marble
>   * Limestone
>   * Basalt
> * Tinkers Construct
>   
>   * ~~Aluminum Brass~~

I will not be touching any materials added by TiC itself.

> * Thermal Expension
>   
>   * Signalum
>   * Lumium
>   * Enderium
>   * Mithrillium (Mana Infused)
>   * Iridium
> * Redstone Arsenal
>   
>   * Flux Crystal
>   * Fluxed Electrum
> * TechReborn
>   
>   * Zinc
>   * Chromium
>   * Tungsten
>   * Titanium
>   * Iridium
>   * Refined Iron
>   * Brass
>   * Tungstensteel
>   * Advanced Alloy
>   * Ruby
>   * Sapphire
>   * Peridot
>   * Red Garnet
>   * Yellow Garnet
> * Mekanism
>   
>   * Osmium
>   * Refined Obsidian
>   * Refined Glowstone
> * Forestry
>   
>   * Apatite
> * Applied Energetics
>   
>   * Certus Quartz
>   * Fluix Quartz
> * Refined Storage
>   
>   * Quartz Enriched Iron
> * ProjectRed
>   
>   * Red Alloy
>   * Electrotine Alloy
>   * Ruby
>   * Sapphire
>   * Peridot
> * Extreme Reactors
>   
>   * Uranium
>   * Yellorium
>   * Cyanite
>   * Blutorium
>   * Lucidrite
>   * Graphite
> * Avaritia
>   
>   * Crystal Matrix
>   * Infinity
>   * Neutronium
> * Actually Additions
>   
>   * Black Quartz
>   * Redstonia
>   * Palis
>   * Diamatine
>   * Emeradic
>   * Enori
>   * Void
> * Draconic Evolution
>   
>   * Draconium
>   * Awakened Draconium
> * Thaumcraft
>   
>   * Thaumium
>   * Void
> * Botania
>   
>   * Living Wood
>   * Living Stone
>   * Manasteel
>   * Terrasteel
>   * Elementium
>   * Gaia Spirit
>   * Mana Diamond
>   * Dragon Stone
>   * Red Quartz
>   * Blaze Quartz
>   * Sunny Quartz
>   * Elven Quartz
>   * Mana Quartz
>   * Lavender Quartz
>   * Smokey Quartz
> * Psi
>   
>   * Psigem
>   * Psimetal
>   * Ebony
>   * Ivory
> * Quark
>   
>   * Biotite
> * Embers
>   
>   * Drawstone
> * Astral Sorcery
>   
>   * Aquamarine
>   * Starmetal
> * ProjectE
>   
>   * Dark Matter
>   * Red Matter
> * Better With Mods
>   
>   * Soulforge Steel
>   * Hellfire
As for the rest, I'll consider them one by one :)

**Comment by Hypsellis** [comment]
Why not vanilla ones ? It would be really nice and coherent to support them as well.

**Comment by YaibaToKen** [comment]
If the TiC Devs decided against it, I won't be the one to step on their toes.

**Comment by Hypsellis** [comment]
Nobody decided anything against anything. TCon devs supported the materials they wanted, you can support the ones you want as well since it's your mod.

**Comment by YaibaToKen** [comment]
Yes, and like I said, I'd like to keep vanilla materials in line with what the TiC Devs did :)

**Comment by SirAron111** [comment]
Adding to the list of popular Materials in 1.12.2:
https://the-midnight-mod.fandom.com/wiki/Ores
https://the-betweenlands.fandom.com/wiki/Category:Minerals
